name: Build and deploy Angular app to Github Pages
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: Deploy to Github Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist/status-tracker-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
